# Site settings
course_name: Learning in Robotics
course_description: "A robot is a machine that senses its environment using sensors, interacts with this environment using actuators to perform a given task and does so efficiently using previous experience of performing similar tasks. We will cover the fundamentals of these three aspects of robotics: perception, planning and learning. A tentative list of topics includes state estimation (EKF, UKF, Particle Filters, visual-inertial odometry), control and planning (LQR, MDPs, sampling-based planning, bayesian methods), reinforcement learning (policy gradients, Q-learning, Imitation Learning, Offline RL) and some miscellaneous topics (meta-learning and formal verification). The coursework will have both applied and theoretical aspects. This is a graduate level class; undergraduates will need permission from the instructor to enroll. Some experience with, or appreciation of, robotics is recommended."
course_semester: "Fall 2022"

baseurl: "https://linklab-uva.github.io/robotlearning" # the subpath of your site, e.g. /blog/
url: "https://linklab-uva.github.io" # the base hostname & protocol for your site

schoolname: "University of Virginia"
#schoolurl: "https://hogwarts.edu"
#twitter_username: username

address: |
    151 Engineer's Way
    Olsson Hall - Link Lab
    Charlottesville, VA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-NFRE4D2LJT

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
