# Site settings
course_name: Learning in Robotics
course_description: "We will cover the mathematical foundations of robotics in this graduate-level course. We will rigorously explore the three pillars of robotics: perception, planning, and control. We’ll commence with theoretical discussions on state estimation methods, including the Kalman Filter, EKF, UKF, and Particle Filters, progress to mapping and visual odometry, and then navigate the intricacies of dynamic programming, control, and planning methods such as LQR and MDPs. Our journey will culminate in reinforcement learning models for robotics, like policy gradients and Q-learning, and specialized topics like foundation models for robotics. To ensure practical application, students will undertake programming assignments addressing real-world robotics challenges. While primarily for graduate students, undergraduates may enroll with the instructor’s approval."
course_semester: "Spring 2025"

baseurl: "/robotlearning" # the subpath of your site, e.g. /blog/
url: "https://linklab-uva.github.io" # the base hostname & protocol for your site

schoolname: "University of Virginia"
#schoolurl: "https://hogwarts.edu"
#twitter_username: username

address: |
    151 Engineer's Way
    Olsson Hall - Link Lab
    Charlottesville, VA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-NFRE4D2LJT

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
